/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.iesb.ppc.apresentacao;

import br.iesb.ppc.entidade.GerenciarGrade;
import br.iesb.ppc.negocio.BO;
import br.iesb.ppc.negocio.FormGradeBO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author tom
 */
public class FormGrade extends javax.swing.JDialog {

    /**
     * Creates new form FormGrade
     */
    public FormGrade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalidadeRadioButton = new javax.swing.ButtonGroup();
        modalidadeLabel = new javax.swing.JLabel();
        radioEAD = new javax.swing.JRadioButton();
        radioPresencial = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cursoComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        turmaComboBox = new javax.swing.JComboBox<>();
        voltarFormGrade = new javax.swing.JButton();
        continuarFormGrade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        modalidadeLabel.setText("Modalidade:*");

        modalidadeRadioButton.add(radioEAD);
        radioEAD.setText("EAD");
        radioEAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEADActionPerformed(evt);
            }
        });

        modalidadeRadioButton.add(radioPresencial);
        radioPresencial.setText("Presencial");
        radioPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPresencialActionPerformed(evt);
            }
        });

        jLabel2.setText("Curso:");

        cursoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Turma:");

        turmaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaComboBoxActionPerformed(evt);
            }
        });

        voltarFormGrade.setText("Voltar");
        voltarFormGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFormGradeActionPerformed(evt);
            }
        });

        continuarFormGrade.setText("Continuar");
        continuarFormGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarFormGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cursoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modalidadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioEAD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioPresencial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turmaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continuarFormGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voltarFormGrade)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidadeLabel)
                    .addComponent(radioEAD)
                    .addComponent(radioPresencial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cursoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(turmaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarFormGrade)
                    .addComponent(continuarFormGrade))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarFormGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFormGradeActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarFormGradeActionPerformed

    private void continuarFormGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarFormGradeActionPerformed
        FormGerenciarGrade formGrade = new FormGerenciarGrade(new javax.swing.JFrame(), true);
        this.dispose();
    }//GEN-LAST:event_continuarFormGradeActionPerformed

    private void radioEADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEADActionPerformed
        FormGrade();
    }//GEN-LAST:event_radioEADActionPerformed

    private void radioPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPresencialActionPerformed
        FormGrade();
    }//GEN-LAST:event_radioPresencialActionPerformed

    private void cursoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoComboBoxActionPerformed
        nomeCurso = (String) cursoComboBox.getSelectedItem();
        
        FormGrade(nomeCurso);
    }//GEN-LAST:event_cursoComboBoxActionPerformed

    private void turmaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaComboBoxActionPerformed
//        nomeCurso = (String) cursoComboBox.getSelectedItem();
//        
//        FormGrade(nomeCurso, turma);
    }//GEN-LAST:event_turmaComboBoxActionPerformed

    private void FormGrade(){
        GerenciarGrade gerenciarGrade = new GerenciarGrade();
        
        if(radioEAD.isSelected()){
            gerenciarGrade.setModalidadeTipo(1);
        }else if(radioPresencial.isSelected()){
            gerenciarGrade.setModalidadeTipo(2);
        }
        cursoComboBox.removeAllItems();
        turmaComboBox.removeAllItems();
        
        BO<GerenciarGrade> bo = new FormGradeBO();
        
        try {
            List<GerenciarGrade> lista = bo.listar();
            
            DefaultComboBoxModel modelCurso = new DefaultComboBoxModel();

            while(!lista.isEmpty()){
                modelCurso.addElement(lista);
            }
            cursoComboBox.setModel(modelCurso);
            
            nomeCurso = (String) cursoComboBox.getSelectedItem();
            
            FormGrade(nomeCurso);
        } catch (Exception e) {
            int tipoMsg = JOptionPane.WARNING_MESSAGE;
            if (e.getCause() != null) {
                tipoMsg = JOptionPane.ERROR_MESSAGE;
            }
            JOptionPane.showMessageDialog(this, e.getMessage(), "Mensagem", tipoMsg);
        }
    }

    private List FormGrade(String nomeCurso){
        GerenciarGrade gerenciarGrade = new GerenciarGrade();
        
        gerenciarGrade.setNomeCurso(nomeCurso);
        
        BO<GerenciarGrade> bo = new FormGradeBO();
        
        try {
            List<GerenciarGrade> listaTurma = bo.listarTurma();
            
            DefaultComboBoxModel modelTurma = new DefaultComboBoxModel();
            
            while(!listaTurma.isEmpty()){
                modelTurma.addElement(listaTurma);
            }
            cursoComboBox.setModel(modelTurma);
        } catch (Exception e) {
            int tipoMsg = JOptionPane.WARNING_MESSAGE;
            if (e.getCause() != null) {
                tipoMsg = JOptionPane.ERROR_MESSAGE;
            }
            JOptionPane.showMessageDialog(this, e.getMessage(), "Mensagem", tipoMsg);
        }
        return turma;
    }
    
    private String nomeCurso;
    private List turma;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarFormGrade;
    private javax.swing.JComboBox<String> cursoComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel modalidadeLabel;
    private javax.swing.ButtonGroup modalidadeRadioButton;
    private javax.swing.JRadioButton radioEAD;
    private javax.swing.JRadioButton radioPresencial;
    private javax.swing.JComboBox<String> turmaComboBox;
    private javax.swing.JButton voltarFormGrade;
    // End of variables declaration//GEN-END:variables

}
